[package]
name = "rami-node"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "rami_node"
path = "src/lib.rs"

[[bin]]
name = "rami-node"
path = "src/main.rs"

[dependencies]
rami-core = { path = "../rami-core" }
rami-net = { path = "../rami-net" }
rami-wallet = { path = "../rami-wallet" }
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
rand_core.workspace = true
# Auto-actualizador: descarga el instalador oficial y verifica su SHA-256.
sha2.workspace = true
ureq.workspace = true

[dev-dependencies]
sha2.workspace = true
hex.workspace = true
